{{ if and .Values.InternalPath .Values.PVCName }}
  {{ required "InternalPath and PVCName should not both be set" .Values.Error_DoNotSet }}
{{ end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "globus-connect.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ template "globus-connect.fullname" . }}
      chart: {{ template "globus-connect.chart" . }}
      release: {{ .Release.Name }}
      instance: {{ .Values.Instance | quote }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "globus-connect.fullname" . }}
        chart: {{ template "globus-connect.chart" . }}
        release: {{ .Release.Name }}
        instance: {{ .Values.Instance | quote }}
        instanceID: {{ .Values.SLATE.Instance.ID | quote  }}
    spec:
      volumes:
      {{ if .Values.InternalPath }}
      - name: dfs-volume
        hostPath:
        # directory location on host
          path: {{ .Values.InternalPath }}
      {{ end }}
      {{ if .Values.PVCName }}
      - name: pvc-volume
        persistentVolumeClaim:
        # use the requested PVC:
          claimName: {{ .Values.PVCName }}
      {{ end }}
      {{ if and .Values.CustomIdentityMapping .Values.GlobusIdentityConfig }}
      - name: {{ .Values.GlobusIdentityConfig }}-volume
        secret:
          secretName: {{ .Values.GlobusIdentityConfig }}
          items:
          - key: mapping
            path: mapping
      {{ end }}
      {{ if .Values.GlobusRestrictConfig }}
      - name: {{ .Values.GlobusRestrictConfig }}-volume
        secret:
          secretName: {{ .Values.GlobusRestrictConfig }}
          items:
          - key: restrictions
            path: restrictions
      {{ end }}
      - name: {{ template "globus-connect.fullname" . }}-passwd
        secret:
          secretName: {{ .Values.GlobusPasswdSecret }}
          items:
          - key: passwd
            path: passwd
      hostNetwork: true
      containers:
      - name: "gcs5"
        image: hub.opensciencegrid.org/slate/globus-connect-v5:{{ .Chart.AppVersion }}
        imagePullPolicy: Always
        command: ["/usr/local/bin/gcs-setup.sh"]
        env:
        - name: GLOBUS_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.GlobusCredentialSecret }}
              key: GLOBUS_CLIENT_ID
        - name: GLOBUS_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Values.GlobusCredentialSecret }}
              key: GLOBUS_CLIENT_SECRET
        - name: DEPLOYMENT_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.GlobusCredentialSecret }}
              key: DEPLOYMENT_KEY
        {{ if .Values.EndpointConfiguration }}
        - name: ENDPOINT_CONFIGURATION
          value: TRUE
        {{ end }}
        - name: COLLECTION_DOMAINS
          value: {{ cat "--domain" (join " - " .Values.StorageConfig.Domain | replace "-" " --domain ") }}
        {{ if .Values.StorageConfig.AllowedUsers }}
        - name: ALLOW_USERS
          value: {{ cat "--user-allow" (join "-" .Values.StorageConfig.AllowedUsers | replace "-" " --user-allow ") }}
        {{ end }}
        {{ if .Values.StorageConfig.DeniedUsers }}
        - name: DENY_USERS
          value: {{ cat "--user-deny" (join "-" .Values.StorageConfig.DeniedUsers | replace "-" " --user-deny ") }}
        {{ end }}
        {{ if eq ( lower .Values.StorageConfig.StorageType ) "posix" }}
        {{ if .Values.StorageConfig.PosixConfig.AllowedGroups }}
        - name: POSIX_ALLOW_GROUPS
          value: {{ cat "--posix-group-allow" (join "-" .Values.StorageConfig.PosixConfig.AllowedGroups | replace "-" " --posix-group-allow ") }}
        {{ end }}
        {{ if .Values.StorageConfig.PosixConfig.DeniedGroups }}
        - name: POSIX_DENY_GROUPS
          value: {{ cat "--posix-group-deny" (join "-" .Values.StorageConfig.PosixConfig.DeniedGroups | replace "-" " --posix-group-deny ") }}
        {{ end }}
        - name: STORAGE_CREATION_ARGS
          value: "storage-gateway create posix "
        {{ end }}
        {{ if eq ( lower .Values.StorageConfig.StorageType ) "ceph" }}
        - name: STORAGE_CREATION_ARGS
          value: "storage-gateway create ceph --s3-endpoint {{ .Values.StorageConfig.CephConfig.S3Endpoint }} --ceph-admin-key-id {{ .Values.StorageConfig.CephConfig.AdminKey }} --ceph-admin-secret-key {{ .Values.StorageConfig.CephConfig.SecertKey }}  --bucket {{ .Values.StorageConfig.CephConfig.Bucket }} "
        {{ end }}
        - name: COLLECTION_PATH
          value: {{ .Values.CollectionConfig.BasePath }}
        - name: COLLECTION_NAME
          value: {{ .Values.CollectionConfig.DisplayName }}
        {{ if .Values.CollectionConfig.Department }}
        - name: COLLECTION_DEPARTMENT
          value: {{ .Values.CollectionConfig.Department }}
        {{ end }}
        {{ if .Values.CollectionConfig.Organization }}
        - name: COLLECTION_ORGANIZATION
          value: {{ .Values.CollectionConfig.Organization }}
        {{ end }}
        {{ if .Values.CollectionConfig.ContactEmail }}
        - name: COLLECTION_EMAIL
          value: {{ .Values.CollectionConfig.ContactEmail }}
        {{ end }}
        {{ if .Values.CollectionConfig.ContactInfo }}
        - name: COLLECTION_CONTACT_INFO
          value: {{ .Values.CollectionConfig.ContactInfo }}
        {{ end }}
        {{ if .Values.CollectionConfig.Description }}
        - name: COLLECTION_DESCRIPTION
          value: {{ .Values.CollectionConfig.Description }}
        {{ end }}
        - name: COLLECTION_IDENTITY
          value: {{ .Values.CollectionConfig.IdentityId }}
        {{ if .Values.CollectionConfig.UserMessage }}
        - name: COLLECTION_USER_MESSAGE
          value: {{ .Values.CollectionConfig.UserMessage }}
        {{ end }}
        {{ if .Values.NodeSetupArgs }}
        - name: NODE_SETUP_ARGS
          value: {{ .Values.NodeSetupArgs }}
        {{ end }}
        - name: TERM
          value: "xterm"
        volumeMounts:
        - name: {{ template "globus-connect.fullname" . }}-passwd
          mountPath: "/root/passwd"
          subPath: passwd        
        {{ if and .Values.ExternalPath .Values.InternalPath }}
        - name: dfs-volume
          mountPath: {{ .Values.ExternalPath }}
        {{ end }}
        {{ if and .Values.ExternalPath .Values.PVCName }}
        - name: pvc-volume
          mountPath: {{ .Values.ExternalPath }}
        {{ end }}
        {{ if and .Values.CustomIdentityMapping .Values.GlobusIdentityConfig }}
        - name: mapping-volume
          mountPath: "/root/identity_mapping.json"
          subPath: mapping
        {{ end }}
        {{ if and .Values.RestrictPaths .Values.GlobusRestrictConfig }}
        - name: restriction-volume
          mountPath: "/root/restrictions.json"
          subPath: restriction
        {{ end }}
      {{ if .Values.NodeSelector }}
      nodeSelector:
        {{ .Values.NodeSelector }}: "true"
      {{ end }}
