name: Incubator Release

on:
  push:
    branches:
      - master

jobs:
  helm-repo:
    name: Helm Repo
    uses: slateci/github-actions/.github/workflows/chart-repo-release.yml@v2
    secrets:
      gh_token: "${{ secrets.GITHUB_TOKEN }}"
