name: Incubator Release

on:
  push:
    branches:
      - master

jobs:
  helm-repo:
    name: Helm Repo
    uses: slateci/github-actions/.github/workflows/chart-repo-release.yml@v9
    secrets:
      gh_token: "${{ secrets.GITHUB_TOKEN }}"

  notifications:
    runs-on: ubuntu-20.04
    needs:
      - helm-repo
    if: ${{ always() && (needs.helm-repo.result == 'failure') }}

    steps:
      - name: Notify Slack of Failure
        uses: slateci/github-actions/.github/actions/slack-notify-failure@v10
        with:
          slack_bot_token: '${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}'
